name: CI

on:
  push:
    branches:
      - main

jobs:
  format_lua:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .config/nvim
