name: CI

on:
  push:
    branches:
      - main

jobs:
  format_lua:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: .config/nvim

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'style: format files by CI'
